projects:
  capstoneoutreach:
    schemaPath: amplify/backend/api/capstoneoutreach/build/schema.graphql
    includes:
      - src/index.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src
        region: us-east-2
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
